import { useEffect,useMemo,useRef,useState } from "react";
import { ArrowLeft,Copy,Download,Image as ImageIcon,Sparkles,WandSparkles } from "lucide-react";

type Analysis={brightness:number;contrast:number;saturation:number;temperature:"warm"|"cool"|"balanced";orientation:string;palette:string[]};
type Post={title:string;caption:string;hashtags:string[];tip:string};
export default function SocialPostStudioPage({onBack}:{onBack:()=>void}){
 const[image,setImage]=useState<string|null>(null),[context,setContext]=useState(""),[analysis,setAnalysis]=useState<Analysis|null>(null),[busy,setBusy]=useState(false);const[brightness,setBrightness]=useState(100),[contrast,setContrast]=useState(100),[saturation,setSaturation]=useState(100),[crop,setCrop]=useState<"4:5"|"1:1"|"9:16">("4:5");const canvas=useRef<HTMLCanvasElement>(null);const sample=useRef(false);
 const post=useMemo(()=>analysis?buildPost(analysis,context,sample.current):null,[analysis,context]);
 function choose(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;sample.current=false;setContext(fileHint(f.name));setImage(URL.createObjectURL(f));}
 async function loadExample(){const b=await fetch("/examples/dubai-evening.png").then(r=>r.blob());sample.current=true;setContext("Dubai evening skyline and city lights");setImage(URL.createObjectURL(b));}
 useEffect(()=>{if(!image)return;setBusy(true);analyzeImage(image).then(a=>{setAnalysis(a);setBrightness(a.brightness<90?112:a.brightness>175?94:103);setContrast(a.contrast<42?112:104);setSaturation(a.saturation<35?112:104);setBusy(false)});},[image]);
 function exportImage(){if(!image||!canvas.current)return;const [rw,rh]=crop.split(":").map(Number);const img=new Image();img.onload=()=>{const c=canvas.current!;c.width=1080;c.height=Math.round(1080*rh/rw);const ctx=c.getContext("2d")!;ctx.filter=`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`;const target=rw/rh,sr=img.width/img.height;let sw=img.width,sh=img.height,sx=0,sy=0;if(sr>target){sw=img.height*target;sx=(img.width-sw)/2}else{sh=img.width/target;sy=(img.height-sh)/2}ctx.drawImage(img,sx,sy,sw,sh,0,0,c.width,c.height);c.toBlob(b=>{if(!b)return;const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`nexora-instagram-${crop.replace(":","x")}.png`;a.click();URL.revokeObjectURL(u)},"image/png")};img.src=image}
 const copy=()=>post&&navigator.clipboard.writeText(`${post.title}\n\n${post.caption}\n\n${post.hashtags.join(" ")}`);
 return <section className="work-page social-studio"><button className="work-back" onClick={onBack}><ArrowLeft size={15}/> All tools</button><header className="work-hero"><span className="eyebrow">CREATIVE INTELLIGENCE</span><h1>Social Post Studio</h1><p>Turn a photo into an Instagram-ready image, caption and hashtag set. Image measurements stay in your browser.</p></header><div className="social-layout">
  <section className="work-card social-input"><label className="image-picker"><ImageIcon size={22}/><b>Drop or choose a photo</b><span>JPG, PNG or WebP</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={choose}/></label><button className="example-action" onClick={loadExample}><Sparkles size={14}/> Try sample photo</button>{image&&<><label>Photo context <small>helps captions describe the subject accurately</small></label><input className="context-input" value={context} onChange={e=>setContext(e.target.value)} placeholder="e.g. Dubai skyline after sunset"/><div className="crop-tabs">{(["4:5","1:1","9:16"] as const).map(x=><button className={crop===x?"active":""} onClick={()=>setCrop(x)} key={x}>{x}</button>)}</div><div className="controls"><label>Brightness <input type="range" min="70" max="130" value={brightness} onChange={e=>setBrightness(+e.target.value)}/><span>{brightness}%</span></label><label>Contrast <input type="range" min="70" max="135" value={contrast} onChange={e=>setContrast(+e.target.value)}/><span>{contrast}%</span></label><label>Saturation <input type="range" min="70" max="140" value={saturation} onChange={e=>setSaturation(+e.target.value)}/><span>{saturation}%</span></label></div></>}</section>
  <section className="work-card social-preview-card">{image?<><div className={`instagram-preview crop-${crop.replace(":","-")}`}><div className="ig-head"><span className="ig-avatar">N</span><b>nexora.lab</b><span>•••</span></div><img src={image} style={{filter:`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`}}/><div className="ig-actions">♡　⌁　⌯</div>{post&&<div className="ig-copy"><b>{post.title}</b><p>{post.caption}</p><div>{post.hashtags.join(" ")}</div></div>}</div><div className="work-actions"><button className="primary-action" onClick={exportImage}><Download size={14}/> Export image</button><button className="example-action" onClick={copy}><Copy size={14}/> Copy post</button></div></>:<div className="work-empty">Upload a photo to build the post preview.</div>}<canvas ref={canvas} hidden/></section>
  <aside className="work-card social-insights"><span className="eyebrow"><WandSparkles size={12}/> PHOTO READ</span>{busy?<p>Reading pixels…</p>:analysis?<><div className="metric-grid"><div><strong>{analysis.brightness}</strong><span>brightness</span></div><div><strong>{analysis.contrast}</strong><span>contrast</span></div><div><strong>{analysis.temperature}</strong><span>temperature</span></div><div><strong>{analysis.orientation}</strong><span>orientation</span></div></div><p className="palette">{analysis.palette.map(c=><i key={c} style={{background:c}} title={c}/>)}</p><p>{post?.tip}</p><small className="truth-note">Nexora measures the image locally. The context field is used for subject-specific copy because pixel statistics alone cannot reliably identify arbitrary subjects.</small></>:<p>Image analysis will appear here.</p>}</aside>
 </div></section>;
}
function fileHint(name:string){return name.replace(/\.[^.]+$/,"").replace(/[-_]+/g," ").replace(/\b(img|image|photo|dsc)\d*\b/gi,"").trim()}
async function analyzeImage(src:string):Promise<Analysis>{return new Promise(resolve=>{const img=new Image();img.onload=()=>{const c=document.createElement("canvas"),w=96,h=Math.max(1,Math.round(96*img.height/img.width));c.width=w;c.height=h;const x=c.getContext("2d")!;x.drawImage(img,0,0,w,h);const d=x.getImageData(0,0,w,h).data;let lum=0,lum2=0,sat=0,r=0,b=0;const buckets=new Map<string,number>();for(let i=0;i<d.length;i+=16){const R=d[i],G=d[i+1],B=d[i+2],mx=Math.max(R,G,B),mn=Math.min(R,G,B),l=.2126*R+.7152*G+.0722*B;lum+=l;lum2+=l*l;sat+=mx?((mx-mn)/mx)*100:0;r+=R;b+=B;const hex=`#${[R,G,B].map(v=>Math.round(v/48)*48).map(v=>Math.min(255,v).toString(16).padStart(2,"0")).join("")}`;buckets.set(hex,(buckets.get(hex)??0)+1)}const n=d.length/16,avg=lum/n,std=Math.sqrt(Math.max(0,lum2/n-avg*avg));resolve({brightness:Math.round(avg),contrast:Math.round(std),saturation:Math.round(sat/n),temperature:r>b*1.08?"warm":b>r*1.08?"cool":"balanced",orientation:img.width>img.height?"landscape":img.width<img.height?"portrait":"square",palette:[...buckets].sort((a,z)=>z[1]-a[1]).slice(0,5).map(x=>x[0])})};img.src=src})}
function buildPost(a:Analysis,context:string,isSample:boolean):Post{const subject=(context.trim()||(isSample?"Dubai evening skyline":"this moment")).replace(/^./,x=>x.toUpperCase());const mood=a.brightness<85?"moody":a.saturation>55?"vibrant":a.temperature==="warm"?"warm":"clean";const title=mood==="moody"?`${subject} — After Hours`:mood==="vibrant"?`${subject} in Full Color`:`${subject} — A Moment Worth Keeping`;const caption=`${subject}. ${mood==="moody"?"Deep tones, quiet details and a little atmosphere.":mood==="vibrant"?"Color, energy and the details that made this frame stand out.":"A simple frame with the details doing the talking."} Saved exactly how it felt.`;const tags=["#NexoraMade","#Photography",`#${mood[0].toUpperCase()+mood.slice(1)}Mood`,"#VisualStory","#InstaDaily"];for(const w of context.match(/[A-Za-z]{4,}/g)??[])tags.push(`#${w}`);return{title,caption,hashtags:[...new Set(tags)].slice(0,10),tip:`Suggested treatment: ${a.brightness<90?"lift exposure slightly":"protect highlights"}, ${a.contrast<42?"add definition":"keep contrast controlled"}, and use the ${a.orientation==="portrait"?"4:5":"4:5 crop with a centered focal area"}.`}}
