import type { ParsedDataset } from "../../types/dataset";
import type { DatasetProfile } from "../data/profiler";
import { aggregateDataset } from "../data/aggregationEngine";
import type { AggregationResult } from "../data/aggregationEngine";
import { filterDataset } from "../data/filterEngine";
import { compareDatasetValues } from "./comparisonEngine";
import type { ComparisonResult } from "./comparisonEngine";
import { parseDataQuestion } from "./questionParser";
import type { QuestionParseResult } from "./questionParser";
export type DataQAResult={success:boolean;question:string;answer:string;parser:QuestionParseResult;aggregation:AggregationResult|null;comparison:ComparisonResult|null;reasoning:string[]};
export function answerDataQuestion(question:string,dataset:ParsedDataset,profile:DatasetProfile):DataQAResult{const parsed=parseDataQuestion(question,profile);if(!parsed.success||!parsed.request)return{success:false,question,answer:"I could not confidently understand this question.",parser:parsed,aggregation:null,comparison:null,reasoning:[parsed.explanation]};try{if(parsed.comparison){const c=compareDatasetValues(dataset,{categoryColumn:parsed.comparison.column,values:parsed.comparison.values,operation:parsed.request.operation,valueColumn:parsed.request.valueColumn});return{success:true,question,answer:comparisonAnswer(c,parsed.request.valueColumn),parser:parsed,aggregation:null,comparison:c,reasoning:[`${c.left.label} and ${c.right.label} were compared.`,`${parsed.request.operation.toUpperCase()} was used for the calculation.`]}}const filtered=filterDataset(dataset,parsed.filters);const aggregation=aggregateDataset(filtered.dataset,parsed.request);return{success:true,question,answer:answer(parsed,aggregation),parser:parsed,aggregation,comparison:null,reasoning:reasoning(parsed,aggregation,filtered.originalRowCount,filtered.filteredRowCount)}}catch(e){return{success:false,question,answer:e instanceof Error?e.message:"The calculation could not be completed.",parser:parsed,aggregation:null,comparison:null,reasoning:[parsed.explanation]}}}
function answer(p:QuestionParseResult,r:AggregationResult){const row=r.rows[0],q=p.request;if(!row||!q)return"No matching data was found.";if(q.operation==="count"&&!q.groupByColumn)return p.filters.length?`${fmt(row.value)} records match the requested filters.`:`The dataset contains ${fmt(row.value)} records.`;if(q.groupByColumn&&q.limit===1)return `${row.group} has the ${q.sort==="asc"?"lowest":"highest"} ${word(q.operation)} ${q.valueColumn??"count"} at ${fmt(row.value)}.`;if(!q.groupByColumn)return `The ${word(q.operation)} ${q.valueColumn??"value"} is ${fmt(row.value)}.`;return `Calculated ${word(q.operation)} ${q.valueColumn??"records"} grouped by ${q.groupByColumn} across ${r.totalGroups} groups.`}
function reasoning(p:QuestionParseResult,r:AggregationResult,original:number,filtered:number){const a:string[]=[];p.filters.forEach(f=>a.push(`${f.column} filter applied: ${f.operator} ${f.value}.`));if(p.filters.length)a.push(`Filtering reduced ${original} rows to ${filtered}.`);if(p.detected.valueColumn)a.push(`${p.detected.valueColumn} was used as the metric.`);if(p.detected.groupByColumn)a.push(`${p.detected.groupByColumn} was used to group the result.`);if(p.detected.operation)a.push(`${p.detected.operation.toUpperCase()} was selected.`);a.push(`${r.totalRowsUsed} usable rows were included.`);return a}
function comparisonAnswer(c:ComparisonResult,metric="value"){if(!c.winner)return `${c.left.label} and ${c.right.label} have the same ${metric} at ${fmt(c.left.value)}.`;const w=c.winner===c.left.label?c.left:c.right,l=w===c.left?c.right:c.left;return `${w.label} has the higher ${metric} at ${fmt(w.value)}, compared with ${fmt(l.value)} for ${l.label}.`}
function word(x:string){return({sum:"total",avg:"average",min:"minimum",max:"maximum",count:"count"} as Record<string,string>)[x]??x}function fmt(n:number){return new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(n)}
